---
title: "Balanço de Potência"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Descrição

A ferramenta tem como objetivo avaliar os montantes de potência necessários nos momentos em que o sistema apresenta demanda máxima instantânea com o objetivo de verificar as condições de seu atendimento. Isto é, verificando a possibilidade de déficits e a auxiliando na avaliação de contratação de potência para o sistema. A ferramenta mantém a compatibilidade com a análise energética previamente efetuada.

A ferramenta de balanço de potência foi desenvolvida em linguagem de programação R e sua interface foi desenvolvida com Shiny, que é um pacote R que facilita a criação de aplicações web diretamente do R e utiliza CSS, widgets, html e ações JavaScript para maior flexibilidade. A ferramenta também usa o pacote clpAPI, que é uma Interface R para a API em C do COIN-OR Clp.

### Dependências

Os seguintes pacotes do CRAN são necessários para a execução do BP:

```r
install.packages(shiny, shinythemes, shinybusy, readr, readxl, writexl, dplyr,  stringr, stringi, tidyr, clpAPI, DBI, RSQLite, tictoc, plotly, zoo, scales, parallel, foreach, doParallel, numbers, magrittr)
```

Além disso, é necessária a instalação do pacote `leitorrmpe`, também desenvolvido pela EPE, para a leitura de arquivos dos modelos de planejanemto energético do CEPEL. Ele pode ser baixado através deste [link](https://www.epe.gov.br/pt/publicacoes-dados-abertos/publicacoes/leitor-dos-arquivos-de-entrada-e-saida-dos-modelos-do-planejamento-energetico-do-cepel).

### Excutando o BP

```r
library(epebpr)

aplicacaoBalanco()
```

### Dúvidas e Sugestões

Para dúvidas e sugestões, entrar em contato através do e-mail <modelos.sgr@epe.gov.br>
